name: "Build Godot"
description: "Build a Godot project for multiple platforms"
author: droxpopuli
branding:
  icon: loader
  color: blue
inputs:
  # Path Args
  project-name:
    description: 'Name of the exported binary'
    required: true
  project-dir:
    description: 'Location of Godot project in repository'
    required: false

  # Build Args
  build-preset:
    description: 'Name of the preset in `export_presets.cfg` to use'
    required: true
  build-dir:
    description: 'Optional name of the subdirectory to put exported project in'
    required: false

  # Mode Flags
  run-tests:
    description: 'Run GUT from /tests instead of building (default: false)'
    default: false
  use-latest:
    description: 'Use Stable vs latest (default: stable)'
    default: stable
  debug-mode:
    description: 'Use `--export-debug` (default: false)'
    default: false

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.project-name }}
    - ${{ inputs.project-dir }}

    - ${{ inputs.build-preset }}
    - ${{ inputs.build-dir }}

    - ${{ inputs.run-tests }}
    - ${{ inputs.use-latest }}
    - ${{ inputs.debug-mode }}
